// Fastion - Fashion Product Data
const productsData = [
  {
    id: 1,
    title: "Classic Trench Coat",
    brand: "Maison Verge",
    price: 249.0,
    originalPrice: 349.0,
    rating: 4.9,
    reviews: 214,
    description: "Timeless cotton trench with a tailored fit and removable belt.",
    image: "https://i.ibb.co/rRq0L8qz/dce22bfb5656a814d6fa2ced0baf13e6.jpg",
    stock: 18,
    badge: "bestseller",
    savePercent: 29,
  },
  {
    id: 2,
    title: "Silk Square Scarf",
    brand: "Lumière",
    price: 79.0,
    originalPrice: 0,
    rating: 4.7,
    reviews: 143,
    description: "Hand-printed silk scarf with vibrant seasonal motifs.",
    image: "https://i.ibb.co/YBFfnf1t/1d3cd7923bfd11a65e50637f6e2967bf.jpg",
    stock: 45,
    badge: "new",
  },
  {
    id: 3,
    title: "Leather Tote Bag",
    brand: "Avenue Atelier",
    price: 189.0,
    originalPrice: 249.0,
    rating: 4.8,
    reviews: 328,
    description: "Full-grain leather tote with interior pockets and reinforced handles.",
    image: "https://i.ibb.co/1Y6d6c8x/3d2a0e40c0fe181ce4524739dfb19631.jpg",
    stock: 12,
    badge: "limited",
    savePercent: 24,
  },
  {
    id: 4,
    title: "Slim Fit Denim Jeans",
    brand: "Denim Co.",
    price: 99.0,
    originalPrice: 129.0,
    rating: 4.6,
    reviews: 410,
    description: "Comfort stretch denim with a modern slim silhouette.",
    image: "https://i.ibb.co/VYv8WJ6P/679d28024993c8b7da1953575510e2e5.jpg",
    stock: 36,
    badge: "bestseller",
    savePercent: 23,
  },
  {
    id: 5,
    title: "Cashmere Crewneck Sweater",
    brand: "Nord & Co",
    price: 159.0,
    originalPrice: 199.0,
    rating: 4.9,
    reviews: 276,
    description: "Ultra-soft cashmere in a classic crew cut — lightweight and warm.",
    image: "https://i.ibb.co/Ng9dYKc9/d79951d3b1de5afcbe1f768690f0b1ae.jpg",
    stock: 22,
    badge: "bestseller",
    savePercent: 20,
  },
  {
    id: 6,
    title: "Ankle Leather Boots",
    brand: "Cielo Footwear",
    price: 139.0,
    originalPrice: 179.0,
    rating: 4.7,
    reviews: 198,
    description: "Premium leather boots with cushioned insole and stacked heel.",
    image: "https://i.ibb.co/ZztWdqH2/f97f2ca051b5999e66dea60521d744a4.jpg",
    stock: 14,
    badge: null,
    savePercent: 22,
  },
  {
    id: 7,
    title: "Statement Hoop Earrings",
    brand: "Bijou Studio",
    price: 49.0,
    originalPrice: 0,
    rating: 4.5,
    reviews: 86,
    description: "Lightweight plated hoops that add instant polish to any outfit.",
    image: "https://i.ibb.co/TBV9DtgS/19e676f2c18efe2f7f38b9151c43f4fc.jpg",
    stock: 60,
    badge: "new",
  },
  {
    id: 8,
    title: "Aviator Sunglasses",
    brand: "Solis",
    price: 119.0,
    originalPrice: 149.0,
    rating: 4.6,
    reviews: 154,
    description: "Classic aviator frames with polarized lenses.",
    image: "https://i.ibb.co/Y7pjWDHB/e2bb1e458bfe696b85e66af7ca6dc2bd.jpg",
    stock: 38,
    badge: null,
    savePercent: 20,
  },
  {
    id: 9,
    title: "Wool Fedora Hat",
    brand: "Haberdash",
    price: 69.0,
    originalPrice: 89.0,
    rating: 4.4,
    reviews: 74,
    description: "Structured wool fedora with satin sweatband.",
    image: "https://i.ibb.co/MyZQ82QC/d868e2cfc5f53990953ee2e7a25433d4.jpg",
    stock: 27,
    badge: "new",
    savePercent: 22,
  },
  {
    id: 10,
    title: "Distressed Denim Jacket",
    brand: "Rogue Street",
    price: 119.0,
    originalPrice: 0,
    rating: 4.7,
    reviews: 203,
    description: "Vintage-inspired denim jacket with subtle distressing.",
    image: "https://i.ibb.co/qMf9kBfV/60f560dc355019cb83a8ef94eafc0f51.jpg",
    stock: 31,
    badge: "bestseller",
  },
  {
    id: 11,
    title: "Linen Relaxed Shirt",
    brand: "Coastal Threads",
    price: 59.0,
    originalPrice: 79.0,
    rating: 4.3,
    reviews: 92,
    description: "Breathable linen shirt with a relaxed, airy fit — perfect for warm days.",
    image: "https://i.ibb.co/tp8dh0Td/117c21341a982cba7a166b41d57c42e7.jpg",
    stock: 46,
    badge: null,
    savePercent: 25,
  },
  {
    id: 12,
    title: "Premium Canvas Sneakers",
    brand: "Stride",
    price: 89.0,
    originalPrice: 109.0,
    rating: 4.6,
    reviews: 176,
    description: "Lightweight canvas sneakers with cushioned arch support.",
    image: "https://i.ibb.co/5WkX9PSC/05d7dd30d11220f215fc44c8cdbd16e6.jpg",
    stock: 52,
    badge: "bestseller",
    savePercent: 18,
  },
]

// Promotional Discount Codes
const promoCodes = {
  FLASH30: { code: 'FLASH30', percent: 30, description: '30% off entire order' },
  MEGA50: { code: 'MEGA50', percent: 50, description: '50% off selected items' },
  VIP70: { code: 'VIP70', percent: 70, description: '70% off premium collection' },
}
